version: '3'
services:
  db:
    image: arm64v8/postgres:15.3
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment: &db_environment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      <<: *db_environment
      # Setting for the binding address instead of 127.0.0.1
      BINDING: 0.0.0.0
    tty: true
    stdin_open: true
volumes:
  db-volume: